### ISSUE TITLE
Root permission required

### ISSUE THREAD

**Issue by parro-it** [jabiinfante/node-mouse#1]
It's possible to avoid root permission requirement?
Maybe this depend on my system configuration?

Trying to run example from readme, I got:

``` bash
Error: EACCES: permission denied, open '/dev/input/mice'
    at Error (native)
```

This are default permission for the device:

```
crw-r----- 1 root root 13, 63 nov  5 18:32 /dev/input/mice
```

It work well if I give read permission to other user on the device, but I want to avoid this.

**Comment by jabiinfante** [comment]
I believe the only doable approach is setting the device readable by a group "mouse" for example:

Sometyhing like this might work:
$ cat /usr/lib/udev/rules.d/12-mouse.rules
KERNEL=="mouse?", GROUP="mouse", MODE="660"
KERNEL=="mice", GROUP="mouse", MODE="660"
KERNEL=="event?", GROUP="mouse", MODE="660"

(and then add the user to the mouse group)
